export const supabaseUrl = 'https://mwtenoalqvadgcmyszqe.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dGVub2FscXZhZGdjbXlzenFlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjAxNDYwMiwiZXhwIjoyMDY3NTkwNjAyfQ.5a8gK66zXx9meZqxhu5YGMoMmy4k5SCpVkJi8ubnan0';
export const supabaseServiceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dGVub2FscXZhZGdjbXlzenFlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjAxNDYwMiwiZXhwIjoyMDY3NTkwNjAyfQ.5a8gK66zXx9meZqxhu5YGMoMmy4k5SCpVkJi8ubnan0';
